(function(r){function k(a,b){return f.open(a,b)}function n(a,b,c){a||(a=document.createElement("a"));a.href=g.fallback(b,c);d.popup&&h.listen(a,"click",function(a){k(b,c)&&h.prevent(a)});return a}function m(a,b,c,d,e){if(!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest))return e(Error("Unsupported browser"));var l=new XMLHttpRequest;l.open(a,b,!0);l.withCredentials=!0;l.setRequestHeader("Accept","application/json");c&&l.setRequestHeader("Content-type","application/json");l.onload=d;
l.onerror=e;l.send(c?JSON.stringify(c):null)}var d={serviceId:"email",tld:"",lang:"",host:"login.szn",registerHost:"registrace.seznam",popup:!0,oauth:{client_id:"",redirect_uri:"",state:""}},p=location.hostname.split("."),q=[p.pop()];"dszn"==p.pop()&&(q.unshift("dszn"),q.unshift(p.pop()));d.tld=q.join(".");var h={listen:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)},prevent:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},dispatch:function(a,
b){var c={};b&&(c.detail=b);try{var d=new CustomEvent(a,c);window.dispatchEvent(d)}catch(e){c.type=a,d=c}a="on"+a.replace(/[^a-z]/gi,"");if(a in window)window[a](d)}},g={generic:function(a,b,c){var d=[],e;for(e in c)d.push(encodeURIComponent(e)+"="+encodeURIComponent(c[e]));return"https://"+a+b+(d.length?"?"+d.join("&"):"")},autologin:function(){return this.generic(d.host+"."+d.tld,"/api/v1/autologin",{service:d.serviceId,return_url:location.href})},fallback:function(a,b){if("oauth"==a)return g.oauth();
var c={service:d.serviceId,return_url:location.href};d.lang&&(c.lang=d.lang);b&&(c.username=b);return this.generic(("register"==a?d.registerHost:d.host)+"."+d.tld,"/",c)},popup:function(a,b){if("oauth"==a)return g.oauth();var c={service:d.serviceId,return_url:this.done()};d.lang&&(c.lang=d.lang);b&&(c.username=b);a="register"==a?d.registerHost:d.host;console.log(this.generic(a+"."+d.tld,"/",c));return this.generic(a+"."+d.tld,"/",c)},done:function(){var a={service:d.serviceId,return_url:location.href};
return this.generic(this.loginHost(),"/loginDone",a)},relay:function(){return this.generic(this.loginHost(),"/relay")},loginHost:function(){var a=d.host.split(".")[0],b=d.tld.split(".").length+1;return a+"."+location.hostname.split(".").slice(-b).join(".")},oauth:function(){var a={response_type:"code"},b;for(b in d.oauth)a[b]=d.oauth[b];d.lang&&(a.lang=d.lang);return this.generic(d.host+"."+d.tld,"/api/v1/oauth/auth",a)},consent:function(a){return this.generic(this.loginHost(),"/api/v1"+a,{})}},f=
{_win:null,_messageSource:null,_relay:null,_interval:null,init:function(){h.listen(window,"message",function(a){f.onMessage(a)});if(window.attachEvent||window.msRequestAnimationFrame)this._relay=document.createElement("iframe"),this._relay.src=g.relay(),this._relay.style.display="none"},open:function(a,b){if(this._win&&!this._win.closed)return this._win.focus(),this._win;this._win=window.open(g.popup(a,b),"_blank",this.features());if(!this._win)return null;this._interval=setInterval(function(){f.closeCheck()},
50);this._relay?(document.body.appendChild(this._relay),this._messageSource=this._relay.contentWindow):this._messageSource=this._win;return this._win},close:function(){if(this._win){clearInterval(this._interval);try{this._win.close()}catch(a){}this._win=null}},features:function(){var a=[window.screenX||window.screenLeft||0,window.screenY||window.screenTop||0],b=[window.outerWidth||document.documentElement.offsetWidth,window.outerHeight||document.documentElement.offsetHeight-100],c=[960,630];a=[a[0]+
(b[0]-c[0])/2,a[1]+(b[1]-c[1])/2];c={left:a[0],top:a[1],width:c[0],height:c[1],scrollbars:1};navigator.vendor&&navigator.vendor.match(/apple/i)&&(c.height+=50);a=[];for(var d in c)a.push(d+"="+c[d]);return a.join(",")},onMessage:function(a){this._messageSource&&a.source==this._messageSource&&(a.source.postMessage("confirm","*"),this.close(),h.dispatch("login-done",JSON.parse(a.data)))},closeCheck:function(){this._win.closed&&(this.close(),h.dispatch("login-close"))}};f.init();r.login={cfg:function(a){for(var b in a)d[b]=
a[b]},link:n,open:k,close:function(){return f.close()},autologin:function(){function a(a,c){h.dispatch("autologin-fail",{status:a,message:c})}m("post",g.autologin(),null,function(b){b=b.target;switch(b.status){case 400:case 200:b=JSON.parse(b.responseText);200==b.status?("green"==b.state&&h.dispatch("autologin-done",b),"orange"==b.state&&h.dispatch("autologout-done",b)):a(b.status,b.message);break;default:a(b.status,b.statusMessage)}},function(b){a(0,b.message)})},register:{open:function(){return k("register")},
link:function(a){return n(a,"register")}},oauth:{open:function(){return k("oauth")},link:function(a){return n(a,"oauth")}},consent:{get:function(){function a(a){k--;0<k||h.dispatch("consent",a?{consents:c,euconsent:d,lang:e,rusId:f}:null)}function b(){}var c={},d=null,e=null,f=null,k=3;m("get",g.consent("/euconsent"),null,function(b){var c=JSON.parse(b.target.responseText);200==c.status&&(d=JSON.parse(c.euconsent));a(200==b.target.status)},b);m("get",g.consent("/consent-list/"),null,function(b){var d=
JSON.parse(b.target.responseText);d.consents&&d.consents.forEach(function(a){c[a.aliases[0]||a.name]=a.state});a(200==b.target.status)},b);m("get",g.consent("/user/properties/lang"),null,function(b){var c=JSON.parse(b.target.responseText);c.lang&&(e=c.lang);c.uid&&(f=c.uid);a(200==b.target.status)},b)},set:function(a,b){function c(){}function d(){e--;0<e||h.dispatch("consent-change")}var e=1;m("post",g.consent("/euconsent"),{euconsent:JSON.stringify(b)},d,c);for(var f in a)b=a[f],null!==b&&(e++,m("post",
g.consent("/consent/"+f),{state:b},d,c))}}}})(window);
